version: 1.0.{build}

os:
  - Visual Studio 2017

environment:
  BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\\build"

# Win32 and x64 can be passed to cmake to populate the CMAKE_GENERATOR_PLATFORM
platform:
  - Win32
  - x64

configuration:
  - Release
 #- Debug

init:
  - echo %platform%

install:
  - pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan profile new default --detect
  - if "%platform%"=="Win32" ( conan profile update settings.arch=x86 default )

before_build:
  - mkdir %BUILD_DIR%
  - cd %BUILD_DIR%
  - conan install .. --build=missing
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017" -A %platform%

build:
  parallel: true
  verbosity: minimal
